apiVersion: v1
kind: Service
metadata:
  name: auth-api-service
  namespace: default
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
      nodePort: 30080
  type: NodePort