apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DB_NAME: expense_db
  DB_USER: postgres
  DB_PASSWORD: postgres
  SPRING_DATASOURCE_URL: jdbc:postgresql://expense-db-service:5432/expense_db
